### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /^\s*-?\s (action\s*:\s |local_action\s*:\s |):...

### ISSUE THREAD

**Issue by dlvovsky** [h-hirokawa/atom-autocomplete-ansible#10]
[Enter steps to reproduce below:]

editing line:
- { role: hadoop-users, tags: []}

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [autocomplete-ansible](https://github.com/h-hirokawa/atom-autocomplete-ansible) package, v0.1.5
### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /^\s_-?\s (action\s_:\s |local_action\s*:\s |): [$/: Unterminated character class

```
At /Users/dimitry/.atom/packages/autocomplete-ansible/lib/provider.js:77

SyntaxError: Invalid regular expression: /^\s*-?\s (action\s*:\s |local_action\s*:\s |): [$/: Unterminated character class
    at RegExp (native)
    at Provider.getSuggestions (/Users/dimitry/.atom/packages/autocomplete-ansible/lib/provider.js:77:22)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
  4x -1:49.8.0 core:delete (atom-text-editor.editor.is-focused)
     -1:46.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -1:46.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:43.7.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -1:43.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:42.2.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:41.4.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:40.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:07.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:50.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:50.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:50.4.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:48 core:save (atom-text-editor.editor.is-focused)
  2x -0:19.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:18.4.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -0:09.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```
### Config

``` json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```
### Installed Packages

``` coffee
# User
ansible-snippets, v0.2.0 (inactive)
ansible-vault, v0.2.5 (inactive)
autocomplete-ansible, v0.1.5 (active)
local-history, v3.4.1 (active)
merge-conflicts, v1.4.4 (active)
split-diff, v1.0.5 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by xenithorb** [comment]
I am also seeing this in the same manner on: 

```
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

In my case though, it also starts out with the following stack trace, THEN, the character class one:

```
SyntaxError: Invalid regular expression: /^\s*-?\s+(action\s*:\s+|local_action\s*:\s+|) ($/: Unterminated group
    at RegExp (native)
    at Provider.getSuggestions (/home/xenith/git/dotfiles/.atom/packages/autocomplete-ansible/lib/provider.js:77:22)
    at /usr/lib64/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/lib64/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/lib64/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/lib64/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /usr/lib64/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

**Comment by h-hirokawa** [comment]
@dlvovsky @xenithorb 

Tank you for reporting the bug.
I forgot to escape string to Regexp format.

Please try the new version 0.1.6!
