### ISSUE TITLE
Command failed: parse_ansible.py

### ISSUE THREAD

**Issue by bgblanch** [h-hirokawa/atom-autocomplete-ansible#11]
Command failed: /home/william/.atom/packages/autocomplete-ansible/lib/parse_ansible.py
[DEPRECATION WARNING]: docker is kept for backwards compatibility but usage is 
discouraged. The module documentation details page may explain more about this 
rationale..
This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
Traceback (most recent call last):
  File "/home/william/.atom/packages/autocomplete-ansible/lib/parse_ansible.py", line 64, in <module>
    main()
  File "/home/william/.atom/packages/autocomplete-ansible/lib/parse_ansible.py", line 56, in main
    for lookup in lookup_loader.all():
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/**init**.py", line 389, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 324, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/lookup/filetree.py", line 35, in <module>
    from __main__ import display
ImportError: cannot import name display

**Comment by h-hirokawa** [comment]
@bgblanch 
I found the problem is caused by a lack of care in `filetree.py`, new lookup plugin added in 2.2.
The plugin can be used only from ansible commands (such as `ansible`, `ansible-playbook`...).
I added the code imitating ansible commands to `parse_ansible.py`, so it should be fixed.

**Comment by bgblanch** [comment]
Updated the plugin and the error messages have disappeared.  Not sure what you're referring to with 2.2.  I'm at v0.1.9.

**Comment by h-hirokawa** [comment]
@bgblanch 
Thank you for reviewing !
2.2 means the version of Ansible, not this plugin.
I didn't make it clear.

**Comment by khelkun** [comment]
I have this deprecation warning on Atom 1.25.0 with atom-autocomplete-ansible 0.1.18
