### ISSUE TITLE
Doesn't work on Windows Platform

### ISSUE THREAD

**Issue by Thitho007** [h-hirokawa/atom-autocomplete-ansible#12]
Hello,

It would be awesome if your package can build (and work) on Windows Platform.

The error is below  :
```
Command failed: C:\Python27\python.exe C:\Users\thitho\.atom\packages\autocomplete-ansible\lib/parse_ansible.py
Traceback (most recent call last):
  File "C:\Users\thitho\.atom\packages\autocomplete-ansible\lib/parse_ansible.py", line 6, in <module>
    from ansible.cli.doc import DocCLI
  File "C:\Python27\lib\site-packages\ansible\cli\__init__.py", line 42, in <module>
    from ansible.utils.display import Display
  File "C:\Python27\lib\site-packages\ansible\utils\display.py", line 21, in <module>
    import fcntl
ImportError: No module named fcntl
```

Anyway, Thanks in advance.

**Comment by ellisgeek** [comment]
looks like fnctl is a Linux specific module as it is tied tightly to the Linux system call by the same name.
