### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by choppedpork** [h-hirokawa/atom-autocomplete-ansible#13]
Hello,

I'm using Atom 1.12.7, autocomplete-ansible 0.1.10 and Ansible 2.2.0.0 (all on Debian Linux, issue happens both in jessie and stretch releases) and unfortunately can't get your plugin to work. Every time I open a yaml file I get an error pop-up (contents below). My ansible is installed using pip and I've tried reinstalling (after removing first) it just in case seeing as the recursive loop seems to happen in the ansible code rather than yours but that didn't help. Do let me know if there's any more info I can provide.
```
autocomplete-python traceback output:
Command failed: /usr/bin/python /home/solid/.atom/packages/autocomplete-ansible/lib/parse_ansible.py
Traceback (most recent call last):
  File "/home/solid/.atom/packages/autocomplete-ansible/lib/parse_ansible.py", line 68, in <module>
    main()
  File "/home/solid/.atom/packages/autocomplete-ansible/lib/parse_ansible.py", line 25, in main
    doc_cli.find_modules(path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/doc.py", line 150, in find_modules
    self.find_modules(module)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/doc.py", line 150, in find_modules
    self.find_modules(module)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/doc.py", line 150, in find_modules
    self.find_modules(module)
(...)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/doc.py", line 150, in find_modules
    self.find_modules(module)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/doc.py", line 150, in find_modules
    self.find_modules(module)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/doc.py", line 150, in find_modules
    self.find_modules(module)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/doc.py", line 150, in find_modules
    self.find_modules(module)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/doc.py", line 145, in find_modules
    if os.path.isdir(path):
  File "/usr/lib/python2.7/genericpath.py", line 52, in isdir
    return stat.S_ISDIR(st.st_mode)
  File "/usr/lib/python2.7/stat.py", line 41, in S_ISDIR
    return S_IFMT(mode) == S_IFDIR
RuntimeError: maximum recursion depth exceeded
```

edit: removed some of the repeated lines in the stacktrace

**Comment by h-hirokawa** [comment]
@choppedpork 

Hmm, it seems that your [library path](http://docs.ansible.com/ansible/intro_configuration.html#library) contains infinite recursion.
If the error could be reproduced by executing the following command, the problem should be caused by your setting.

```
$ ansible-doc -l
```

Please check this.

**Comment by choppedpork** [comment]
Thanks @h-hirokawa - I can indeed replicate the issue with `ansible-doc` and it only seems to happen when I execute it from my home directory. Fun times figuring it out ahead of me!
