### ISSUE TITLE
Failed to load the autocomplete-ansible package

### ISSUE THREAD

**Issue by pauloheck** [h-hirokawa/atom-autocomplete-ansible#25]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-ansible](https://github.com/h-hirokawa/atom-autocomplete-ansible) package 0.1.15

### Stack Trace

Failed to load the autocomplete-ansible package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-autocomplete-ansible-0.1.15/lib/provider.js:4:30)
    at /packages/atom-autocomplete-ansible-0.1.15/lib/provider.js:187:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-autocomplete-ansible-0.1.15/lib/main.js:7:17)
    at /packages/atom-autocomplete-ansible-0.1.15/lib/main.js:42:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:903:35)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:617:16)
    at config.transact (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:530:20)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-ansible 0.1.15 
fuzzaldrin 2.1.0 
language-ansible 0.2.1 
linter-ansible-linting 1.3.1 
linter-ansible-syntax 1.2.0 
```

**Comment by h-hirokawa** [comment]
@pauloheck 
Since `fuzzaldrin` is an `npm` package, it is strange that it is treated as an `apm` package.
You should try uninstalling `fuzzaldrin` and re-installing `autocomplete-ansible` with `apm`.

```
apm uninstall fuzzaldrin
apm install autocomplete-ansible
```

**Comment by h-hirokawa** [comment]
Btw, this package doesn't work on Windows unfortunately due to [the limitation of Ansible](http://docs.ansible.com/ansible/latest/intro_windows.html#using-a-windows-control-machine).
