### ISSUE TITLE
parse_ansible.py failed "The lookup aws_account_attribute requires boto3 and botocore"

### ISSUE THREAD

**Issue by khelkun** [h-hirokawa/atom-autocomplete-ansible#31]
I don't succeed to use atom-autocomplete-ansible in Atom. I have the following output on Atom 1.25.0 with atom-autocomplete-ansible 0.1.18
```
Command failed: "/usr/bin/python" "/home/sebastien/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/home/sebastien/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 86, in <module>
    main()
  File "/home/sebastien/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 78, in main
    for lookup in lookup_loader.all():
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 435, in all
    module = self._load_module_source(name, path)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 346, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/lookup/aws_account_attribute.py", line 61, in <module>
    raise AnsibleError("The lookup aws_account_attribute requires boto3 and botocore.")
ansible.errors.AnsibleError: The lookup aws_account_attribute requires boto3 and botocore.
```
Ubuntu 17.10.0 (artful)
ansible --version
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sebastien/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

**Comment by khelkun** [comment]
I didn't pay enough attention to the requierements in the README.md
- Ansible >= 2.2 and Python 2.7 or
- Ansible >= 2.4 and Python >= 3.5
So I did set `/usr/bin/python3.6` in the autocomplete-ansible settings in Atom.
Then I had this message in Atom:
```
autocomplete-ansible unable to import ansible.
Install ansible using pip.
```
So I did:
```
sudo apt install python3-pip
pip3 install ansible
```
But I still get the same error as previously

**Comment by h-hirokawa** [comment]
@khelkun 
Please check ansible is installed correctly.
Can you import ansible in `/usr/bin/python3.6` interpreter?

**Comment by h-hirokawa** [comment]
@khelkun 
Please install `boto3` and `botocore` with pip.

**Comment by khelkun** [comment]
@h-hirokawa, my bad I should have figured that out
Everything's ok now, thanks!
