### ISSUE TITLE
autocomplete-ansible unable to import ansible

### ISSUE THREAD

**Issue by kraeml** [h-hirokawa/atom-autocomplete-ansible#34]
When I start atom, I got this message:

```
autocomplete-ansible unable to import ansible.
Install ansible using pip.
```

With:

```
ansible --version
ansible 2.4.3.0
  config file = /home/user/PROJECT_PATH/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```
PROJECT_PATH is the PATH to my Project.

With:

```
head -1 /usr/local/bin/ansible
#!/usr/bin/python
```

For me it seams all ok or I lost somthing?

By the way, my os is Ubuntu 17.10.

Thanks

kraeml

**Comment by oolongbrothers** [comment]
Hello!

Thanks for your effort making this very useful Atom plugin!

I get the same error pop-up described above whenever I open an ansible file.
This in spite of me actually having installed ansible via pip. This worked still recently with my setup.

OS: Ubuntu 16.04
Atom version: 1.24.1
Python version: 2.7.12
Ansible version: 2.3.3.0

```
$ pip freeze
ansible==2.3.3.0
asn1crypto==0.24.0
bcrypt==3.1.4
cffi==1.11.5
cryptography==2.2.2
enum34==1.1.6
idna==2.6
ipaddress==1.0.19
Jinja2==2.10
MarkupSafe==1.0
paramiko==2.4.1
pkg-resources==0.0.0
pyasn1==0.4.2
pycparser==2.18
pycrypto==2.6.1
PyNaCl==1.2.1
PyYAML==3.12
six==1.11.0
[...]
```

Best regards,
//Alexander

**Comment by oolongbrothers** [comment]
Sorry, I need to qualify my posting above.

The problem only appears when I pip install ansible globally.
When I install ansible into a virtualenv in my project folder, the problem disappears.

Is running ansible from virtualenv a requirement that you added recently for the plugin? In that case it would be helpful if the error message stated that.
Or is this rather a regression bug with global pip installed ansible installations?

//Alexander

**Comment by kraeml** [comment]
@oolongbrothers Thanks with venv ansibel AND boto3 and botocore the **famous** autocomplet-ansible is running.

**Comment by yodatak** [comment]
I got this on fedora 28 ansible 2.5 too
ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/yodatak/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

**Comment by h-hirokawa** [comment]
@yodatak Would you show me the warning message on autocomplete-ansible v0.1.20?

**Comment by Nemie** [comment]
I just updated my autocomplete-ansible package and restarted Atom. Before this update it was working just fine without any complaints.

Got this message:

`**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: "Fedora release
**Thrown From**: [autocomplete-ansible](https://github.com/h-hirokawa/atom-autocomplete-ansible) package 0.1.21


### Stack Trace

Failed to load the autocomplete-ansible package

```
At /home/xxxx/docs/confs/.atom/packages/autocomplete-ansible/libs/provider.js: Unexpected token (46:10)

SyntaxError: /home/xxxx/docs/confs/.atom/packages/autocomplete-ansible/libs/provider.js: Unexpected token (46:10)
          const no_ansible_match = err.message.match(
            /No module named ['"]?ansible/),
          if (no_ansible_match) {
            window.atom.notifications.addWarning(
              'autocomplete-ansible unable to import ansible.', {
                description: `You must install ansible with the following
    at Parser.pp.raise (/app.asar/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/app.asar/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseBindingAtom (/app.asar/node_modules/babylon/lib/parser/lval.js:128:12)
    at Parser.pp.parseVarHead (/app.asar/node_modules/babylon/lib/parser/statement.js:508:18)
    at Parser.parseVarHead (/app.asar/node_modules/babylon/lib/plugins/flow.js:943:13)
    at Parser.pp.parseVar (/app.asar/node_modules/babylon/lib/parser/statement.js:491:10)
    at Parser.pp.parseVarStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:370:8)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:99:19)
    at Parser.parseStatement (/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/app.asar/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:105:19)
    at Parser.parseStatement (/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseIfStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:268:26)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:87:19)
    at Parser.parseStatement (/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/app.asar/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/app.asar/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.parseFunctionBody (/app.asar/node_modules/babylon/lib/plugins/flow.js:643:20)
    at Parser.pp.parseFunction (/app.asar/node_modules/babylon/lib/parser/statement.js:524:8)
    at Parser.pp.parseExprAtom (/app.asar/node_modules/babylon/lib/parser/expression.js:397:19)
    at Parser.parseExprAtom (/app.asar/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExprListItem (/app.asar/node_modules/babylon/lib/parser/expression.js:801:16)
    at Parser.parseExprListItem (/app.asar/node_modules/babylon/lib/plugins/flow.js:819:24)
    at Parser.pp.parseExprList (/app.asar/node_modules/babylon/lib/parser/expression.js:789:20)
    at Parser.pp.parseSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:270:29)
```

### Commands

```
```

### Non-Core Packages

```
ansible-vault 0.6.14 
autocomplete-ansible 0.1.21 
autocomplete-python 1.10.5 
git-plus 7.10.2 
language-ansible 0.2.2 
local-history 4.3.1 
python-tools 0.6.9 
todo-show 2.3.0 
```
`
------------------------
Ansible Version

[xxxx@xxxxxxx ~]$ ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xxxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

**Comment by h-hirokawa** [comment]
@Nemie 
Sorry for my carelessness.
This bug has been fixed in v0.1.22.

**Comment by Nemie** [comment]
Thank you @h-hirokawa it's working now!

**Comment by pupseba** [comment]
Hi!

I think I'm facing this issue:
· ansible --version
ansible 2.7.0
  config file = None
  configured module search path = [u'/home/sebas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:26:09) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]

I'm using the flatpak version of Atom 1.35.0 x64

I do have installed ansible with the required command of: 
"/usr/bin/python3.7 -m pip install ansible"

Yet I keep getting this message saying "autocomoplete-ansible unable to import ansible".

Although I've tried with a few configs, based on the git page instructions for this project, I'm trying to use python3.7, also tried with the result of the "head -1" command (which in my case is /usr/bin/python2) but also no luck.

Any idea what could I do?

Thanks!

**Comment by dvershinin** [comment]
Happenned to me on RHEL 8, when I had set Python 2.7 to be the default alternative for when you run `python`.

So this fixed it:

    alternatives --set python /usr/bin/python3
