### ISSUE TITLE
Failed to activate the autocomplete-ansible package

### ISSUE THREAD

**Issue by golovinan** [h-hirokawa/atom-autocomplete-ansible#38]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: "Fedora release
**Thrown From**: [autocomplete-ansible](https://github.com/h-hirokawa/atom-autocomplete-ansible) package 0.1.22

### Stack Trace

Failed to activate the autocomplete-ansible package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/r
/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-autocomplete-ansible/libs/provider.js:4:30)
    at /packages/atom-autocomplete-ansible/libs/provider.js:201:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-autocomplete-ansible/libs/main.js:7:17)
    at /packages/atom-autocomplete-ansible/libs/main.js:42:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:220:40)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
```

### Commands

```
```

### Non-Core Packages

```
ansi-to-utf8 0.4.0 
ansible-galaxy 0.2.1 
ansible-galaxy-plus 1.1.4 
ansible-snippets 0.2.0 
autocomplete-ansible 0.1.22 
atom-autocomplete-php 0.25.6 
fetch 0.3.0 
jQuery 1.2.6 
atom-linter-phpstan 1.0.1 
show-invisibles-plus 0.3.1 
atom-solidity-linter 0.0.11 
atom-tab-close-always-visible 1.1.0 
autocomplete-ansible 0.1.22 
autocomplete-modules 2.0.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
custom-invisibles 0.1.2 
Ensime 0.41.0 
fuzzaldrin 2.1.0 
Hydrogen 2.5.0 
hyperclick 0.1.5 
intentions 1.1.5 
language-ansi 1.1.1 
language-ansible 0.2.2 
language-ansible 0.2.2 
language-mode-transitional 0.0.2 
language-scala 1.1.9 
leak-detector 0.2.1 
linter 2.2.0 
linter-ansible-syntax 1.2.0 
linter-flexible-survival 3.6.0 
linter-ui-default 1.7.1 
regex-railroad-diagram 0.19.4 
transition-grammar 0.3.1 
```

**Comment by h-hirokawa** [comment]
@golovinan 
It seems strange because fuzzaldrin should be automatically installed when you install the package.
Please try re-installing autocomplete-ansible with apm.

```
apm uninstall autocomplete-ansible
apm install autocomplete-ansible
```

**Comment by dnorthup-ums** [comment]
No feedback for over a year. Closing
