### ISSUE TITLE
autocomplete failed on mac OS X 10.11.4

### ISSUE THREAD

**Issue by kenneyhe** [h-hirokawa/atom-autocomplete-ansible#42]
Command failed: "/usr/local/bin/python" "/Users/kenneyhe/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
expect:
  installation and work

actual:
Traceback (most recent call last):
  File "/Users/kenneyhe/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 9, in <module>
    from ansible.cli.doc import DocCLI
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 35, in <module>
    from ansible import constants as C
  File "/usr/local/lib/python2.7/site-packages/ansible/constants.py", line 161, in <module>
    DEFAULT_LOCAL_TMP         = get_config(p, DEFAULTS, 'local_tmp',        'ANSIBLE_LOCAL_TEMP',      '$HOME/.ansible/tmp', istmppath=True)
  File "/usr/local/lib/python2.7/site-packages/ansible/constants.py", line 81, in get_config
    makedirs_safe(value, 0o700)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/path.py", line 67, in makedirs_safe
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/$HOME/.ansible/tmp): [Errno 13] Permission denied: '/$HOME'

steps to repo:
  install ansible autocomplete 0.1.24
  open yams
  select ansible advance

**Comment by dnorthup-ums** [comment]
This isn't a package bug. Check your directory permissions and make sure they match up with the permissions of the user that Atom is being run as.
