### ISSUE TITLE
autocomplete-ansible give error traceback, when ansible installed with pip

### ISSUE THREAD

**Issue by scorobo** [h-hirokawa/atom-autocomplete-ansible#46]
atom 1.41.0 x64 

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

When open Atom:
Command failed: "/usr/bin/python" "/home/al/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/home/al/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 35, in <module>
    doc_cli = DocCLI([])
  File "/home/al/.local/lib/python3.6/site-packages/ansible/cli/doc.py", line 58, in __init__
    super(DocCLI, self).__init__(args)
  File "/home/al/.local/lib/python3.6/site-packages/ansible/cli/__init__.py", line 67, in __init__
    raise ValueError('A non-empty list for args is required')
ValueError: A non-empty list for args is required

After doc-cli installed via pip:

Command failed: "/usr/bin/python" "/home/al/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/home/al/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 35, in <module>
    doc_cli = DocCLI([])
  File "/home/al/.local/lib/python3.6/site-packages/ansible/cli/doc.py", line 58, in __init__
    super(DocCLI, self).__init__(args)
  File "/home/al/.local/lib/python3.6/site-packages/ansible/cli/__init__.py", line 67, in __init__
    raise ValueError('A non-empty list for args is required')
ValueError: A non-empty list for args is required

**Comment by ebenezar-mccoy** [comment]
@scorobo dude, read the different topic that already has fix for that https://github.com/h-hirokawa/atom-autocomplete-ansible/issues/44

**Comment by scorobo** [comment]
It works! Thank you!
