### ISSUE TITLE
Ansible 4.0.0: AttributeError: module 'ansible.utils.plugin_docs' has no attribute 'BLACKLIST'

### ISSUE THREAD

**Issue by k0ste** [h-hirokawa/atom-autocomplete-ansible#61]
```python
Command failed: "/usr/local/Cellar/ansible/4.0.0/libexec/bin/python" "/Users/k0ste/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/Users/k0ste/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 20, in <module>
    BLACKLIST_MODULES = plugin_docs.BLACKLIST['MODULE']
AttributeError: module 'ansible.utils.plugin_docs' has no attribute 'BLACKLIST'
```

**Comment by z-deniz** [comment]
i have the same issue

**Comment by gunman808** [comment]
Same here. I think it is now called REJECTLIST.
https://docs.ansible.com/ansible/latest/user_guide/plugin_filtering_config.html

**Comment by dnorthup-ums** [comment]
@k0ste @z-deniz & @gunman808 
What version(s) of Ansible & Python are the three of you using?

**Comment by k0ste** [comment]
@dnorthup-ums 

```shell
√ ~ % ansible --version
ansible [core 2.11.0]
  config file = None
  configured module search path = ['/Users/k0ste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.0.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/k0ste/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
```

**Comment by dnorthup-ums** [comment]
Looks like ansible/ansible#70028 swapped out the lists one-for-one. Once I've figured out how to test for it a change shouldn't be that complicated.

**Comment by dnorthup-ums** [comment]
Ok, I've tested out a patch against python 2.7.x / ansible 2.9.x, python 3.6.9 / ansible 2.10.10, and python 3.6.9 / ansible 2.11.1. I'll put together a PR, etc... It might take a day or two for me to push out the new revision.

**Comment by dnorthup-ums** [comment]
For those willing to apply the change manually, see the linked PR... As the CI for this repo has broken again I cannot currently merge anything.

**Comment by ghost** [comment]
Tried the patch : excellent. Thank you :)

**Comment by walterrowe** [comment]
The PR above resolved this for me.

```
 % ansible-playbook --version
ansible-playbook [core 2.11.6] 
  config file = None
  configured module search path = ['/Users/wrowe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.7.0_1/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/wrowe/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```

```
Command failed: "/usr/local/Cellar/ansible/4.7.0_1/libexec/bin/python" "/Users/wrowe/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/Users/wrowe/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 20, in <module>
    BLACKLIST_MODULES = plugin_docs.BLACKLIST['MODULE']
AttributeError: module 'ansible.utils.plugin_docs' has no attribute 'BLACKLIST'
```


```
try:
    from ansible.plugins.loader import lookup_loader, module_loader
    from ansible.utils import plugin_docs
    use_old_loader = False
    BLACKLIST_MODULES = plugin_docs.BLACKLIST['MODULE']
except ImportError:
    from ansible.plugins import lookup_loader, module_loader
    from ansible.utils import module_docs as plugin_docs
    use_old_loader = True
    BLACKLIST_MODULES = plugin_docs.BLACKLIST_MODULES
```

**Comment by ParpingTam** [comment]
I applied the patch but was still having some issues about a missing key 'module_blacklist'.

I ended up with the following line in my ~/.ansible.cfg file:

`PLUGIN_FILTERS_CFG  = /etc/ansible/filter_plugins.yml`

And the following in the /etc/ansible/filter_plugins.yml file:

```
---
filter_version: '1.0'
module_rejectlist:
module_blacklist:
```

**Comment by Moppiman** [comment]
I hope that's helps, the plugin_docs.BLACKLIST['MODULE'] has changed to plugin_docs.REJECTLIST['MODULE'].
And i set 'from ansible.plugin_docs import *'

```js
try:
    from ansible.plugins.loader import lookup_loader, module_loader
    # from ansible.utils import plugin_docs
    from ansible.plugin_docs import *
    use_old_loader = False
    BLACKLIST_MODULES = plugin_docs.REJECTLIST['MODULE']
    # BLACKLIST_MODULES = plugin_docs.BLACKLIST['MODULE']
except ImportError:
    from ansible.plugins import lookup_loader, module_loader
    from ansible.utils import module_docs as plugin_docs
    use_old_loader = False
    BLACKLIST_MODULES = plugin_docs.BLACKLIST_MODULE
```

**Comment by dnorthup-ums** [comment]
As Atom is discontinued this extension is also, alas I don't have the access needed to mark it as such.
